---
# This playbook does a rolling update for all servers serially (one at a time).
# Change the value of serial: to adjust the number of server to be updated.

- hosts: mysql
  sudo: yes
  serial: 1
  
  roles:
  - common
  - mysql

- hosts: percona
  sudo: yes
  serial: 1
  
  roles:
  - common
  - percona

- hosts: mariadb
  sudo: yes
  serial: 1
  
  roles:
  - common
  - mariadb

- hosts: turbo-hipster
  sudo: yes
  serial: 1
  
  roles:
  - turbo-hipster
