---
# This playbook deploys alll of the turbo-hipter software stack to all the servers.  

# Apply common configuration to all hosts
- hosts: all
  sudo: yes
  roles:
  - common
  - users

- hosts: mysql
  sudo: yes
  roles:
  - mysql

- hosts: percona
  sudo: yes
  roles:
  - percona

- hosts: mariadb
  sudo: yes
  roles:
  - mariadb

- hosts: turbo-hipster
  sudo: yes
  roles:
  - turbo-hipster
