---
# Handler to manage the turbo-hipster role. 

- name: install turbo-hipster
  raw: cd {{ th_repo_destination }} && /usr/bin/python setup.py install --record files.txt &&  cp -r {{ th_repo_destination }}/etc /

- name: create turbo-hipster directories
  raw: mkdir -p /var/log/turbo-hipster/ /var/cache/pip && chown turbo-hipster:turbo-hipster -R /var/log/turbo-hipster/ && chmod 777 /var/cache/pip

- name: restart turbo-hipster
  service: name=turbo-hipster state=restarted


- name: extract datasets
  command: whoami  
