---
# Handler to manage the turbo-hipster role. 

- name: install turbo-hipster
  raw: cd {{ th_repo_destination }} && /usr/bin/python setup.py install --record files.txt &&  cp -r {{ th_repo_destination }}/etc /

- name: create turbo-hipster directories
  raw: mkdir -p /var/log/turbo-hipster/ /var/cache/pip {{ th_dataset_path }}/git {{ th_dataset_path }}/jobs  && chown {{ th_user }}:{{ th_user }} -R /var/log/turbo-hipster/ && chmod 777 /var/cache/pip

#- name: extract datasets
#  unarchive: src=turbo-hipster-datasets.tar.bz2 dest=/  

- name: set dataset permissions
  command: chown {{ th_user }}:{{ th_user }} -R {{ th_dataset_path }}

- name: deploying config file - config.json
  template: src=config.json.j2 dest=/etc/turbo-hipster/config.json owner=root mode=0644

- name: restart turbo-hipster
  service: name=turbo-hipster state=restarted

