---
# This role will install MySQL, and secure it.

- name: Install Mysql package
  apt: pkg={{ item }} state=present
  with_items:
   - mysql-server
   - mysql-client
   - mysqltuner
   - python-mysqldb

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ db_root_password }}
  with_items:
   - $ansible_hostname
   - 127.0.0.1
   - ::1
   - localhost

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  service: name={{ db_engine }} state=started enabled=true

- name: copy .my.cnf file with root password credentials
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600


- name: delete anonymous MySQL server user for $server_hostname
  mysql_user: name="" host=$server_hostname state=absent

- name: delete anonymous MySQL server user for localhost
  mysql_user: name="" state=absent

- name: remove the MySQL test database
  mysql_db: name=test state=absent
