---

# Apache is handled by the base-apache role upstream
- name: Install php and git 
  apt: pkg={{ item }} state=present
  with_items:
   - php5
   - php5-mysql
   - git

- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/test/
