---
# This role contains common plays that will run on all nodes.

- name: install common packages
  apt: pkg={{ item }} state=present
  with_items:
   - vim
   - tcpdump
   - htop

- name: Setup vim
  copy: src=vimrc dest=/etc/vim/vimrc

- name: Install ntp 
  apt: pkg=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=true
  tags: ntp
